config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :orders, only: [:new, :create] do
    get 'success', on: :member
    get 'failure', on: :member
  end
  root "home#index"
  get 'generate_images/generate', to: 'generate_images#generate'
  get 'generate_images/show', to: 'generate_images#show_image', as: 'show_image'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user

  enum status: {
    pending: 0,
    paid: 1,
    failed: 2
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/generate_images_controller.rb
require "rmagick"

class GenerateImagesController < ApplicationController
  def generate
    img = Magick::Image.new(300, 200) do |i|
        i.background_color = 'red'
    end

    # draw text
    draw = Magick::Draw.new
    draw.font = 'Helvetica'
    draw.pointsize = 25
    draw.gravity = Magick::CenterGravity

    # Annotate the image with the first line of text in the center
    draw.annotate(img, 0, 0, 0, -40, "Hello, World!") do |txt|
      txt.fill = 'white'
    end

    draw.annotate(img, 0, 0, 0, 0, "This is a second line.") do |txt|
      txt.fill = 'white'
    end

    draw.annotate(img, 0, 0, 0, 40, "And a third line here.") do |txt|
      txt.fill = 'white'
    end

    # Save the image to the public images directory
    img.write(Rails.root.join('public', 'images', 'hello_world.jpg'))

    redirect_to action: :show_image
  end

  def show_image
    render 'show_image'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!

    def new
        @amount = 5000 #amount in cents
    end

    def create
        byebug
        begin
            customer = if current_user.stripe_customer_id.blank?
                            Stripe::Customer.create(email: current_user.email)
                       else
                            Stripe::Customer.retrieve(current_user.stripe_customer_id)
                       end
                       
            customer.sources.create(source: 'tok_1OzGozSAYMjwg6v5Z4CVIAi5')

            charge = Stripe::Charge.create(
                customer: customer.id,
                amount: params[:amount],
                description: 'Rails Stripe Customer',
                currency: 'usd'
            )

            @order = current_user.orders.create(amount: params[:amount], stripe_charge_id: charge.id)

            current_user.update(stripe_customer_id: customer.id) if current_user.stripe_customer_id.blank?

            redirect_to order_success_path(@order), notice: "Payment was successful!"

        rescue Stripe::CardError => e
            flash[:error] = e.message
            redirect_to order_failure_path
        rescue => e
            flash[:error] = "There was an error processing your payment: #{e.message}"
            redirect_to new_order_path
        end
    end

    def success
        @order = Order.find(params[:id])
        @order.update(status: :paid)
    end
    
    def failure
        render :failure
    end

    private

    def order_params
        params.require(:order).permit(:amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generate_image_helper.rb
module GenerateImageHelper
end

app/helpers/generate_images_helper.rb
module GenerateImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/generate_images/show_image.html.erb
<h1>Generated Image</h1>
<%= image_tag '/images/hello_world.jpg' %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      .logout-link {
        position: absolute;
        top: 10px;
        right: 20px;
        font-weight: bold;
        font-size: x-large;
      }
    </style>
  </head>
  <body>
    <h1>Demo Application</h1>

    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "logout-link" %>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeIntegrationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Flash messages for Devise -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/orders/failure.html.erb
<h1>Payment Failed</h1>
<p>There was an error processing your payment.</p>
<p><%= flash[:error] %></p>

app/views/orders/new.html.erb
<%= form_with(url: orders_path, method: :post, local: true) do |form| %>
  <div class="field">
    <label>Amount</label>
    <%= text_field_tag :amount, @amount %>
  </div>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>"
        data-amount="<%= @amount %>"
        data-name="Stripe Payment"
        data-description="Stripe Payment for Test Product"
        data-email="<%= current_user.email %>"
        data-currency="usd">
  </script>
<% end %>

app/views/orders/success.html.erb
<h1>Payment Successful</h1>
<p>Thank you for your payment.</p>
<p>Order ID: <%= @order.id %></p>
<p>Amount: $<%= @order.amount / 100.0 %></p>